name: CI

on:
  push:
    branches: [ main, testing ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
      fail-fast: false


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Get full python version
      id: full-python-version1
      run: |
        echo ::set-output name=version:: \
          $(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")
      
    - name: Setup Workspace
      run: |
        sh ./dev.sh setup-dev
        pytest --cov=./src --cov-report=xml

    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittest
        verbose: true
